#!/usr/bin/env python

"""
This module contains the schema for the database. With table names, column names
and table structures defined as constants.
"""

# ID Master table
# - This table is used to store the master id used to link the different identifiers
TABLE_NAME_ID_MASTER = "id_master"

COLUMN_NAME_MASTER_ID = "master_id"

TABLE_STRUCTURE_PROTEINS = f"""
{COLUMN_NAME_MASTER_ID} UUID PRIMARY KEY,
"""


# Locs tags table
# - This table is used to store the locus tags and link them to the master id
TABLE_NAME_LOCUS_TAGS = "locus_tags"

COLUMN_NAME_LOCUS_TAG = "locus_tag"

TABLE_STRUCTURE_LOCUS_TAGS = f"""
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_MASTER_ID} UUID REFERENCES {TABLE_NAME_ID_MASTER}({COLUMN_NAME_MASTER_ID}),
"""


# UniProtKB table
TABLE_NAME_UNIPROT = "uniprot"

COLUMN_NAME_UNIPROT_ACCESSION = "uniprot_accession"
COLUMN_NAME_LOCUS_TAG = "locus_tag"
COLUMN_NAME_ORF_NAME = "orf_name"
COLUMN_NAME_KEGG_ACCESSION = "kegg_accession"
COLUMN_NAME_EMBL_PROTEIN_ID = "embl_protein_id"
COLUMN_NAME_REFSEQ_ACCESSION = "refseq_accession"
COLUMN_NAME_KEYWORDS = "keywords"
COLUMN_NAME_PROTEIN_NAME = "protein_name"
COLUMN_NAME_PROTEIN_EXISTENCE = "protein_existence"
COLUMN_NAME_SEQUENCE = "sequence"
COLUMN_NAME_GO_TERM = "go_term"
COLUMN_NAME_EC_NUMBER = "ec_number"
COLUMN_NAME_POST_TRANSLATIONAL_MODIFICATION = "ptm"

TABLE_STRUCTURE_UNIPROT = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_ORF_NAME} VARCHAR(20)[],
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20)[],
{COLUMN_NAME_EMBL_PROTEIN_ID} VARCHAR(20),
{COLUMN_NAME_REFSEQ_ACCESSION} VARCHAR(20),
{COLUMN_NAME_KEYWORDS} VARCHAR(20)[],
{COLUMN_NAME_PROTEIN_NAME} VARCHAR(255),
{COLUMN_NAME_PROTEIN_EXISTENCE} VARCHAR(255),
{COLUMN_NAME_SEQUENCE} TEXT,
{COLUMN_NAME_GO_TERM} VARCHAR(20)[],
{COLUMN_NAME_EC_NUMBER} VARCHAR(20)[],
{COLUMN_NAME_POST_TRANSLATIONAL_MODIFICATION} JSONB
"""


# RefSeq table
TABLE_NAME_REFSEQ = "refseq"

COLUMN_NAME_REFSEQ_LOCUS_TAG = "refseq_locus_tag"
COLUMN_NAME_STRAND_LOCATION = "strand_location"
COLUMN_NAME_START_POSITION = "start_position"
COLUMN_NAME_END_POSITION = "end_position"
COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE = "translated_protein_sequence"

TABLE_STRUCTURE_REFSEQ = f"""
{COLUMN_NAME_REFSEQ_LOCUS_TAG} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_REFSEQ_ACCESSION} VARCHAR(2,
{COLUMN_NAME_STRAND_LOCATION} VARCHAR(20),
{COLUMN_NAME_START_POSITION} INT,
{COLUMN_NAME_END_POSITION} INT,
{COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE} TEXT
"""


# KEGG table
TABLE_NAME_KEGG = "kegg"

COLUMN_NAME_KEGG_ACCESSION = "kegg_accession"
COLUMN_NAME_KEGG_PATHWAY = "kegg_pathway"
COLUMN_NAME_KEGG_ORTHOLOGY = "kegg_orthology"

TABLE_STRUCTURE_KEGG = f"""
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20)[],
{COLUMN_NAME_KEGG_ORTHOLOGY} VARCHAR(20)[]
"""


# KEGG Relations table
TABLE_NAME_KEGG_RELATIONS = "kegg_relations"

COLUMN_NAME_KEGG_RELATION_SOURCE = "source"
COLUMN_NAME_KEGG_RELATION_TARGET = "target"
COLUMN_NAME_KEGG_RELATION_TYPE = "type"
COLUMN_NAME_KEGG_RELATION_SUBTYPE = "subtype"
COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME = "subtype_name"

TABLE_STRUCTURE_KEGG_RELATIONS = f"""
{COLUMN_NAME_KEGG_RELATION_SOURCE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TARGET} VARCHAR(20),
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TYPE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_SUBTYPE} VARCHAR(20)[],
{COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME} VARCHAR(20)[]
PRIMARY KEY (
    {COLUMN_NAME_KEGG_RELATION_SOURCE}
    {COLUMN_NAME_KEGG_RELATION_TARGET},
    {COLUMN_NAME_KEGG_PATHWAY},
    {COLUMN_NAME_KEGG_RELATION_TYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME}
"""


# STRING table
TABLE_NAME_STRING_INTERACTIONS = "string_interactions"

COLUMN_NAME_PROTEIN_A = "protein_a"
COLUMN_NAME_PROTEIN_B = "protein_b"
COLUMN_NAME_NEIGHBORHOOD = "neighborhood"
COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED = "neighborhood_transferred"
COLUMN_NAME_FUSION = "fusion"
COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE = "phylogenetic_cooccurrence"
COLUMN_NAME_HOMOLOGY = "homology"
COLUMN_NAME_COEXPRESSION = "coexpression"
COLUMN_NAME_COEXPRESSION_TRANSFERRED = "coexpression_transferred"
COLUMN_NAME_EXPERIMENTAL = "experimental"
COLUMN_NAME_EXPERIMENTAL_TRANSFERRED = "experimental_transferred"
COLUMN_NAME_DATABASE = "database"
COLUMN_NAME_DATABASE_TRANSFERRED = "database_transferred"
COLUMN_NAME_TEXTMINING = "textmining"
COLUMN_NAME_TEXTMINING_TRANSFERRED = "textmining_transferred"
COLUMN_NAME_COMBINED_SCORE = "combined_score"

TABLE_STRUCTURE_STRING_INTERACTIONS = f"""
{COLUMN_NAME_PROTEIN_A} VARCHAR(20),
{COLUMN_NAME_PROTEIN_B} VARCHAR(20),
{COLUMN_NAME_NEIGHBORHOOD} INTEGER,
{COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED} INTEGER,
{COLUMN_NAME_FUSION} INTEGER,
{COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE} INTEGER,
{COLUMN_NAME_HOMOLOGY} INTEGER,
{COLUMN_NAME_COEXPRESSION} INTEGER,
{COLUMN_NAME_COEXPRESSION_TRANSFERRED} INTEGER,
{COLUMN_NAME_EXPERIMENTAL} INTEGER,
{COLUMN_NAME_EXPERIMENTAL_TRANSFERRED} INTEGER,
{COLUMN_NAME_DATABASE} INTEGER,
{COLUMN_NAME_DATABASE_TRANSFERRED} INTEGER,
{COLUMN_NAME_TEXTMINING} INTEGER,
{COLUMN_NAME_TEXTMINING_TRANSFERRED} INTEGER,
{COLUMN_NAME_COMBINED_SCORE} INTEGER,
PRIMARY KEY ({COLUMN_NAME_PROTEIN_A}, {COLUMN_NAME_PROTEIN_B})
"""



