#!/usr/bin/env python

"""
This module contains the schema for the database. With table names, column names
and table structures defined as constants.
"""

# ID Master table
# - This table is used to store the master id used to link the different identifiers
TABLE_NAME_ID_MASTER = "id_master"

COLUMN_NAME_MASTER_ID = "master_id"

TABLE_STRUCTURE_PROTEINS = f"""
{COLUMN_NAME_MASTER_ID} UUID PRIMARY KEY,
"""


# Locs tags table
# - This table is used to store the locus tags and link them to the master id
TABLE_NAME_LOCUS_TAGS = "locus_tags"

COLUMN_NAME_LOCUS_TAG = "locus_tag"

TABLE_STRUCTURE_LOCUS_TAGS = f"""
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_MASTER_ID} UUID REFERENCES {TABLE_NAME_ID_MASTER}({COLUMN_NAME_MASTER_ID}),
"""


# UniProtKB table
TABLE_NAME_UNIPROT = "uniprot"

COLUMN_NAME_UNIPROT_ACCESSION = "uniprot_accession"
COLUMN_NAME_LOCUS_TAG = "locus_tag"
COLUMN_NAME_ORF_NAME = "orf_name"
COLUMN_NAME_KEGG_ACCESSION = "kegg_accession"
COLUMN_NAME_EMBL_PROTEIN_ID = "embl_protein_id"
COLUMN_NAME_REFSEQ_ACCESSION = "refseq_accession"
COLUMN_NAME_KEYWORDS = "keywords"
COLUMN_NAME_PROTEIN_NAME = "protein_name"
COLUMN_NAME_PROTEIN_EXISTENCE = "protein_existence"
COLUMN_NAME_SEQUENCE = "sequence"
COLUMN_NAME_GO_TERM = "go_term"
COLUMN_NAME_EC_NUMBER = "ec_number"
COLUMN_NAME_POST_TRANSLATIONAL_MODIFICATION = "ptm"

TABLE_STRUCTURE_UNIPROT = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_ORF_NAME} VARCHAR(20)[],
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20)[],
{COLUMN_NAME_EMBL_PROTEIN_ID} VARCHAR(20),
{COLUMN_NAME_REFSEQ_ACCESSION} VARCHAR(20),
{COLUMN_NAME_KEYWORDS} VARCHAR(20)[],
{COLUMN_NAME_PROTEIN_NAME} VARCHAR(255),
{COLUMN_NAME_PROTEIN_EXISTENCE} VARCHAR(255),
{COLUMN_NAME_SEQUENCE} TEXT,
{COLUMN_NAME_GO_TERM} VARCHAR(20)[],
{COLUMN_NAME_EC_NUMBER} VARCHAR(20)[],
{COLUMN_NAME_POST_TRANSLATIONAL_MODIFICATION} JSONB
"""


# RefSeq table
TABLE_NAME_REFSEQ = "refseq"

COLUMN_NAME_REFSEQ_LOCUS_TAG = "refseq_locus_tag"
COLUMN_NAME_STRAND_LOCATION = "strand_location"
COLUMN_NAME_START_POSITION = "start_position"
COLUMN_NAME_END_POSITION = "end_position"
COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE = "translated_protein_sequence"

TABLE_STRUCTURE_REFSEQ = f"""
{COLUMN_NAME_REFSEQ_LOCUS_TAG} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_REFSEQ_ACCESSION} VARCHAR(2,
{COLUMN_NAME_STRAND_LOCATION} VARCHAR(20),
{COLUMN_NAME_START_POSITION} INT,
{COLUMN_NAME_END_POSITION} INT,
{COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE} TEXT
"""


# KEGG table
TABLE_NAME_KEGG = "kegg"

COLUMN_NAME_KEGG_ACCESSION = "kegg_accession"
COLUMN_NAME_KEGG_PATHWAY = "kegg_pathway"
COLUMN_NAME_KEGG_ORTHOLOGY = "kegg_orthology"

TABLE_STRUCTURE_KEGG = f"""
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20)[],
{COLUMN_NAME_KEGG_ORTHOLOGY} VARCHAR(20)[]
"""


# KEGG Relations table
TABLE_NAME_KEGG_RELATIONS = "kegg_relations"

COLUMN_NAME_KEGG_RELATION_SOURCE = "source"
COLUMN_NAME_KEGG_RELATION_TARGET = "target"
COLUMN_NAME_KEGG_RELATION_TYPE = "type"
COLUMN_NAME_KEGG_RELATION_SUBTYPE = "subtype"
COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME = "subtype_name"

TABLE_STRUCTURE_KEGG_RELATIONS = f"""
{COLUMN_NAME_KEGG_RELATION_SOURCE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TARGET} VARCHAR(20),
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TYPE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_SUBTYPE} VARCHAR(20)[],
{COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME} VARCHAR(20)[]
PRIMARY KEY (
    {COLUMN_NAME_KEGG_RELATION_SOURCE}
    {COLUMN_NAME_KEGG_RELATION_TARGET},
    {COLUMN_NAME_KEGG_PATHWAY},
    {COLUMN_NAME_KEGG_RELATION_TYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME}
)
"""


# STRING table
TABLE_NAME_STRING_INTERACTIONS = "string_interactions"

COLUMN_NAME_PROTEIN_A = "protein_a"
COLUMN_NAME_PROTEIN_B = "protein_b"
COLUMN_NAME_NEIGHBORHOOD = "neighborhood"
COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED = "neighborhood_transferred"
COLUMN_NAME_FUSION = "fusion"
COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE = "phylogenetic_cooccurrence"
COLUMN_NAME_HOMOLOGY = "homology"
COLUMN_NAME_COEXPRESSION = "coexpression"
COLUMN_NAME_COEXPRESSION_TRANSFERRED = "coexpression_transferred"
COLUMN_NAME_EXPERIMENTAL = "experimental"
COLUMN_NAME_EXPERIMENTAL_TRANSFERRED = "experimental_transferred"
COLUMN_NAME_DATABASE = "database"
COLUMN_NAME_DATABASE_TRANSFERRED = "database_transferred"
COLUMN_NAME_TEXTMINING = "textmining"
COLUMN_NAME_TEXTMINING_TRANSFERRED = "textmining_transferred"
COLUMN_NAME_COMBINED_SCORE = "combined_score"

TABLE_STRUCTURE_STRING_INTERACTIONS = f"""
{COLUMN_NAME_PROTEIN_A} VARCHAR(20),
{COLUMN_NAME_PROTEIN_B} VARCHAR(20),
{COLUMN_NAME_NEIGHBORHOOD} INTEGER,
{COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED} INTEGER,
{COLUMN_NAME_FUSION} INTEGER,
{COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE} INTEGER,
{COLUMN_NAME_HOMOLOGY} INTEGER,
{COLUMN_NAME_COEXPRESSION} INTEGER,
{COLUMN_NAME_COEXPRESSION_TRANSFERRED} INTEGER,
{COLUMN_NAME_EXPERIMENTAL} INTEGER,
{COLUMN_NAME_EXPERIMENTAL_TRANSFERRED} INTEGER,
{COLUMN_NAME_DATABASE} INTEGER,
{COLUMN_NAME_DATABASE_TRANSFERRED} INTEGER,
{COLUMN_NAME_TEXTMINING} INTEGER,
{COLUMN_NAME_TEXTMINING_TRANSFERRED} INTEGER,
{COLUMN_NAME_COMBINED_SCORE} INTEGER,
PRIMARY KEY ({COLUMN_NAME_PROTEIN_A}, {COLUMN_NAME_PROTEIN_B})
"""


# Experimental Condition table
TABLE_NAME_EXPERIMENTAL_CONDITION = "experimental_condition"

COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME = "name"
COLUMN_NAME_EXPERIMENTAL_CONDITION_DESCRIPTION = "description"
COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE = "type"

TABLE_STRUCTURE_EXPERIMENTAL_CONDITION = f"""
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) PRIMARY KEY,
{COLUMN_NAME_EXPERIMENTAL_CONDITION_DESCRIPTION} TEXT,
{COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE} VARCHAR(255),
ADD CONSTRAINT {COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE}_check CHECK (
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE} IN (
        'transcriptomics',
        'proteomics',
        'phosphoproteomics',
    )
)
"""


# Transcriptomics table
TABLE_NAME_TRANSCRIPTOMICS = "transcriptomics"

COLUMN_NAME_EXPERIMENTAL_ID = "experimental_id"
COLUMN_NAME_CONDITION_A = "condition_a"
COLUMN_NAME_CONDITION_B = "condition_b"
COLUMN_NAME_LOG2_FOLD_CHANGE = "log2_fold_change"
COLUMN_NAME_P_VALUE = "p_value"
COLUMN_NAME_ADJUSTED_P_VALUE = "adjusted_p_value"

TABLE_STRUCTURE_TRANSCRIPTOMICS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_CONDITION_A} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_CONDITION_B} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_LOG2_FOLD_CHANGE} DOUBLE PRECISION,
{COLUMN_NAME_P_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_ADJUSTED_P_VALUE} DOUBLE PRECISION,
PRIMARY KEY ({COLUMN_NAME_EXPERIMENTAL_ID}, {COLUMN_NAME_CONDITION_A}, {COLUMN_NAME_CONDITION_B})
"""


# Transcriptomics Counts table
TABLE_NAME_TRANSCRIPTOMICS_COUNTS = "transcriptomics_counts"

COLUMN_NAME_REPLICATE = "replicate"
COLUMN_NAME_READ_COUNT = "read_count"
COLUMN_NAME_NORMALIZED_COUNT = "normalized_count"

TABLE_STRUCTURE_TRANSCRIPTOMICS_COUNTS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_REPLICATE} INTEGER,
{COLUMN_NAME_READ_COUNT} DOUBLE PRECISION,
{COLUMN_NAME_NORMALIZED_COUNT} DOUBLE PRECISION,
PRIMARY KEY ({COLUMN_NAME_EXPERIMENTAL_ID}, {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}, {COLUMN_NAME_REPLICATE})
"""


# Proteomics Peptide Modifications table
TABLE_NAME_PROTEOMICS_PEPTIDE_MODIFICATIONS = "proteomics_peptide_modifications"

# COLUMN_NAME_EXPERIMENTAL_ID
# EXPERIMENTAL_CONDITION_NAME
COLUMN_NAME_MODIFICATION_TYPE = "modification_type"
COLUMN_NAME_MODIFICATION_POSITION = "modification_position"
COLUMN_NAME_PEPTIDE_SEQUENCE = "peptide_sequence"
COLUMN_NAME_START_POSITION_COMPLETE_PROTEIN = "start_position_complete_protein"
COLUMN_NAME_END_POSITION_COMPLETE_PROTEIN = "end_position_complete_protein"
COLUMN_NAME_PSM_AMBIGUITY = "psm_ambiguity"
COLUMN_NAME_PEP = "pep"
COLUMN_NAME_Q_VALUE = "q_value"
COLUMN_NAME_SEARCH_ENGINE_CONFIDENCE = "search_engine_confidence"

TABLE_STRUCTURE_PROTEOMICS_PEPTIDE_MODIFICATIONS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_MODIFICATION_TYPE} VARCHAR(255),
{COLUMN_NAME_MODIFICATION_POSITION} TEXT,
{COLUMN_NAME_PEPTIDE_SEQUENCE} TEXT,
{COLUMN_NAME_START_POSITION_COMPLETE_PROTEIN} INTEGER,
{COLUMN_NAME_END_POSITION_COMPLETE_PROTEIN} INTEGER,
{COLUMN_NAME_PSM_AMBIGUITY} TEXT,
{COLUMN_NAME_PEP} DOUBLE PRECISION,
{COLUMN_NAME_Q_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_SEARCH_ENGINE_CONFIDENCE} TEXT,
PRIMARY KEY (
    {COLUMN_NAME_EXPERIMENTAL_ID},
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME},
    {COLUMN_NAME_MODIFICATION_TYPE},
    {COLUMN_NAME_MODIFICATION_POSITION}
)
"""


# Proteomics Quantification table
TABLE_NAME_PROTEOMICS_QUANTIFICATION = "proteomics_quantification"

# COLUMN_NAME_EXPERIMENTAL_ID
# EXPERIMENTAL_CONDITION_NAME
# COLUMN_NAME_REPLICATE
COLUMN_NAME_PROTEIN_SEQUENCE = "protein_sequence"
COLUMN_NAME_SUM_PEP = "sum_pep"
COLUMN_NAME_COMBINED_Q_VALUE = "combined_q_value"
COLUMN_NAME_ABUNDANCE = "abundance"
COLUMN_NAME_ABUNDANCE_NORMALIZED = "abundance_normalized"
COLUMN_NAME_ABUNDANCE_COUNT = "abundance_count"


TABLE_STRUCTURE_PROTEOMICS_QUANTIFICATION = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_REPLICATE} INTEGER,
{COLUMN_NAME_PROTEIN_SEQUENCE} TEXT,
{COLUMN_NAME_SUM_PEP} DOUBLE PRECISION,
{COLUMN_NAME_COMBINED_Q_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE_NORMALIZED} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE_COUNT} DOUBLE PRECISION,
PRIMARY KEY (
    {COLUMN_NAME_EXPERIMENTAL_ID},
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME},
    {COLUMN_NAME_REPLICATE},
    {COLUMN_NAME_PROTEIN_SEQUENCE}
)
"""

