#!/usr/bin/env python

"""
This module contains the schema for the database. With table names, column names
and table structures defined as constants.
"""

# ID Mapper table
# - This table is used to map the IDs of the different databases
TABLE_NAME_ID_MAPPER = "id_mapper"

COLUMN_NAME_UNIPROT_ACCESSION = "uniprot_accession"
COLUMN_NAME_REFSEQ_LOCUS_TAG = "refseq_locus_tag"
COLUMN_NAME_LOCUS_TAG = "locus_tag"
COLUMN_NAME_KEGG_ACCESSION = "kegg_accession"
COLUMN_NAME_REFSEQ_PROTEIN_ID = "refseq_protein_id"

TABLE_STRUCTURE_ID_MAPPER = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20),
{COLUMN_NAME_REFSEQ_LOCUS_TAG} VARCHAR(20),
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20),
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20),
{COLUMN_NAME_REFSEQ_PROTEIN_ID} VARCHAR(20),
UNIQUE (
        {COLUMN_NAME_UNIPROT_ACCESSION},
        {COLUMN_NAME_REFSEQ_LOCUS_TAG},
        {COLUMN_NAME_LOCUS_TAG},
        {COLUMN_NAME_KEGG_ACCESSION},
        {COLUMN_NAME_REFSEQ_PROTEIN_ID}
        )
"""

TABLE_INDEX_ID_MAPPER = f"""
CREATE INDEX ON {TABLE_NAME_ID_MAPPER} ({COLUMN_NAME_UNIPROT_ACCESSION});
CREATE INDEX ON {TABLE_NAME_ID_MAPPER} ({COLUMN_NAME_REFSEQ_LOCUS_TAG});
CREATE INDEX ON {TABLE_NAME_ID_MAPPER} ({COLUMN_NAME_LOCUS_TAG});
CREATE INDEX ON {TABLE_NAME_ID_MAPPER} ({COLUMN_NAME_KEGG_ACCESSION});
CREATE INDEX ON {TABLE_NAME_ID_MAPPER} ({COLUMN_NAME_REFSEQ_PROTEIN_ID});
"""


# UniProtKB table
TABLE_NAME_UNIPROT = "uniprot"

COLUMN_NAME_ORF_NAME = "orf_name"
COLUMN_NAME_EMBL_PROTEIN_ID = "embl_protein_id"
COLUMN_NAME_KEYWORD = "keyword"
COLUMN_NAME_PROTEIN_NAME = "protein_name"
COLUMN_NAME_PROTEIN_EXISTENCE = "protein_existence"
COLUMN_NAME_SEQUENCE = "sequence"
COLUMN_NAME_GO_TERM = "go_term"
COLUMN_NAME_EC_NUMBER = "ec_number"

TABLE_STRUCTURE_UNIPROT = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_ORF_NAME} VARCHAR(20)[],
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20)[],
{COLUMN_NAME_REFSEQ_PROTEIN_ID} VARCHAR(20),
{COLUMN_NAME_EMBL_PROTEIN_ID} VARCHAR(20),
{COLUMN_NAME_PROTEIN_NAME} VARCHAR(255),
{COLUMN_NAME_PROTEIN_EXISTENCE} VARCHAR(255),
{COLUMN_NAME_SEQUENCE} TEXT
"""


# UniProtKB Keywords table
TABLE_NAME_UNIPROT_KEYWORD = "uniprot_keyword"

TABLE_STRUCTURE_UNIPROT_KEYWORD = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20),
{COLUMN_NAME_KEYWORD} VARCHAR(20),
PRIMARY KEY ({COLUMN_NAME_UNIPROT_ACCESSION}, {COLUMN_NAME_KEYWORD}),
FOREIGN KEY ({COLUMN_NAME_UNIPROT_ACCESSION}) REFERENCES {TABLE_NAME_UNIPROT}({COLUMN_NAME_UNIPROT_ACCESSION})
"""

TABLE_INDEX_UNIPROT_KEYWORD = f"""
CREATE INDEX ON {TABLE_NAME_UNIPROT_KEYWORD} ({COLUMN_NAME_UNIPROT_ACCESSION})
"""


# UniProtKB GO Terms table
TABLE_NAME_UNIPROT_GO_TERM = "uniprot_go_term"

TABLE_STRUCTURE_UNIPROT_GO_TERM = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20),
{COLUMN_NAME_GO_TERM} VARCHAR(20),
PRIMARY KEY ({COLUMN_NAME_UNIPROT_ACCESSION}, {COLUMN_NAME_GO_TERM}),
FOREIGN KEY ({COLUMN_NAME_UNIPROT_ACCESSION}) REFERENCES {TABLE_NAME_UNIPROT}({COLUMN_NAME_UNIPROT_ACCESSION})
"""

TABLE_INDEX_UNIPROT_GO_TERM = f"""
CREATE INDEX ON {TABLE_NAME_UNIPROT_GO_TERM} ({COLUMN_NAME_UNIPROT_ACCESSION})
"""


# UniProtKB EC Numbers table
TABLE_NAME_UNIPROT_EC_NUMBER = "uniprot_ec_number"

TABLE_STRUCTURE_UNIPROT_EC_NUMBER = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20),
{COLUMN_NAME_EC_NUMBER} VARCHAR(20),
PRIMARY KEY ({COLUMN_NAME_UNIPROT_ACCESSION}, {COLUMN_NAME_EC_NUMBER}),
FOREIGN KEY ({COLUMN_NAME_UNIPROT_ACCESSION}) REFERENCES {TABLE_NAME_UNIPROT}({COLUMN_NAME_UNIPROT_ACCESSION})
"""

TABLE_INDEX_UNIPROT_EC_NUMBER = f"""
CREATE INDEX ON {TABLE_NAME_UNIPROT_EC_NUMBER} ({COLUMN_NAME_UNIPROT_ACCESSION})
"""


# UniProtKB Post-translational Modifications table
TABLE_NAME_UNIPROT_PTM = "uniprot_ptm"

COLUMN_NAME_UNIPROT_PTM_START = "ptm_start"
COLUMN_NAME_UNIPROT_PTM_END = "ptm_end"
COLUMN_NAME_UNIPROT_PTM_DESCRIPTION = "description"

TABLE_STRUCTURE_UNIPROT_PTM = f"""
{COLUMN_NAME_UNIPROT_ACCESSION} VARCHAR(20),
{COLUMN_NAME_UNIPROT_PTM_START} INTEGER,
{COLUMN_NAME_UNIPROT_PTM_END} INTEGER,
{COLUMN_NAME_UNIPROT_PTM_DESCRIPTION} VARCHAR(255),
PRIMARY KEY ({COLUMN_NAME_UNIPROT_ACCESSION}, {COLUMN_NAME_UNIPROT_PTM_START}, {COLUMN_NAME_UNIPROT_PTM_END}),
FOREIGN KEY ({COLUMN_NAME_UNIPROT_ACCESSION}) REFERENCES {TABLE_NAME_UNIPROT}({COLUMN_NAME_UNIPROT_ACCESSION})
"""

TABLE_INDEX_UNIPROT_PTM = f"""
CREATE INDEX ON {TABLE_NAME_UNIPROT_PTM} ({COLUMN_NAME_UNIPROT_ACCESSION})
"""


# RefSeq table
TABLE_NAME_REFSEQ = "refseq"

COLUMN_NAME_STRAND_LOCATION = "strand_location"
COLUMN_NAME_START_POSITION = "start_position"
COLUMN_NAME_END_POSITION = "end_position"
COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE = "translated_protein_sequence"

TABLE_STRUCTURE_REFSEQ = f"""
{COLUMN_NAME_REFSEQ_LOCUS_TAG} VARCHAR(20) PRIMARY KEY,
{COLUMN_NAME_LOCUS_TAG} VARCHAR(20)[],
{COLUMN_NAME_REFSEQ_PROTEIN_ID} VARCHAR(20)[],
{COLUMN_NAME_STRAND_LOCATION} VARCHAR(20),
{COLUMN_NAME_START_POSITION} VARCHAR(20),
{COLUMN_NAME_END_POSITION} VARCHAR(20),
{COLUMN_NAME_TRANSLATED_PROTEIN_SEQUENCE} TEXT
"""


# KEGG table
TABLE_NAME_KEGG = "kegg"

TABLE_STRUCTURE_KEGG = f"""
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20) PRIMARY KEY
"""


# KEGG Pathways table
TABLE_NAME_KEGG_PATHWAY = "kegg_pathway"

COLUMN_NAME_KEGG_PATHWAY = "kegg_pathway"

TABLE_STRUCTURE_KEGG_PATHWAY = f"""
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20),
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20),
PRIMARY KEY ({COLUMN_NAME_KEGG_ACCESSION}, {COLUMN_NAME_KEGG_PATHWAY})
"""

TABLE_INDEX_KEGG_PATHWAY = f"""
CREATE INDEX ON {TABLE_NAME_KEGG_PATHWAY} ({COLUMN_NAME_KEGG_ACCESSION})
"""


# KEGG KO table
TABLE_NAME_KEGG_KO = "kegg_ko"

COLUMN_NAME_KEGG_ORTHOLOGY = "kegg_orthology"

TABLE_STRUCTURE_KEGG_KO = f"""
{COLUMN_NAME_KEGG_ACCESSION} VARCHAR(20),
{COLUMN_NAME_KEGG_ORTHOLOGY} VARCHAR(20),
PRIMARY KEY ({COLUMN_NAME_KEGG_ACCESSION}, {COLUMN_NAME_KEGG_ORTHOLOGY})
"""

TABLE_INDEX_KEGG_KO = f"""
CREATE INDEX ON {TABLE_NAME_KEGG_KO} ({COLUMN_NAME_KEGG_ACCESSION})
"""


# KEGG Relations table
TABLE_NAME_KEGG_RELATIONS = "kegg_relations"

COLUMN_NAME_KEGG_RELATION_SOURCE = "source"
COLUMN_NAME_KEGG_RELATION_TARGET = "target"
COLUMN_NAME_KEGG_RELATION_TYPE = "type"
COLUMN_NAME_KEGG_RELATION_SUBTYPE = "subtype"
COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME = "subtype_name"

TABLE_STRUCTURE_KEGG_RELATIONS = f"""
{COLUMN_NAME_KEGG_RELATION_SOURCE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TARGET} VARCHAR(20),
{COLUMN_NAME_KEGG_PATHWAY} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_TYPE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_SUBTYPE} VARCHAR(20),
{COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME} VARCHAR(20),
PRIMARY KEY (
    {COLUMN_NAME_KEGG_RELATION_SOURCE},
    {COLUMN_NAME_KEGG_RELATION_TARGET},
    {COLUMN_NAME_KEGG_PATHWAY},
    {COLUMN_NAME_KEGG_RELATION_TYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE},
    {COLUMN_NAME_KEGG_RELATION_SUBTYPE_NAME}
)
"""

TABLE_INDEX_KEGG_RELATIONS = f"""
CREATE INDEX ON {TABLE_NAME_KEGG_RELATIONS} ({COLUMN_NAME_KEGG_RELATION_SOURCE});
CREATE INDEX ON {TABLE_NAME_KEGG_RELATIONS} ({COLUMN_NAME_KEGG_RELATION_TARGET})
"""


# STRING table
TABLE_NAME_STRING_INTERACTIONS = "string_interactions"

COLUMN_NAME_PROTEIN_A = "protein_a"
COLUMN_NAME_PROTEIN_B = "protein_b"
COLUMN_NAME_NEIGHBORHOOD = "neighborhood"
COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED = "neighborhood_transferred"
COLUMN_NAME_FUSION = "fusion"
COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE = "phylogenetic_cooccurrence"
COLUMN_NAME_HOMOLOGY = "homology"
COLUMN_NAME_COEXPRESSION = "coexpression"
COLUMN_NAME_COEXPRESSION_TRANSFERRED = "coexpression_transferred"
COLUMN_NAME_EXPERIMENTAL = "experimental"
COLUMN_NAME_EXPERIMENTAL_TRANSFERRED = "experimental_transferred"
COLUMN_NAME_DATABASE = "database"
COLUMN_NAME_DATABASE_TRANSFERRED = "database_transferred"
COLUMN_NAME_TEXTMINING = "textmining"
COLUMN_NAME_TEXTMINING_TRANSFERRED = "textmining_transferred"
COLUMN_NAME_COMBINED_SCORE = "combined_score"

TABLE_STRUCTURE_STRING_INTERACTIONS = f"""
{COLUMN_NAME_PROTEIN_A} VARCHAR(20),
{COLUMN_NAME_PROTEIN_B} VARCHAR(20),
{COLUMN_NAME_NEIGHBORHOOD} INTEGER,
{COLUMN_NAME_NEIGHBORHOOD_TRANSFERRED} INTEGER,
{COLUMN_NAME_FUSION} INTEGER,
{COLUMN_NAME_PHYLOGENETIC_COOCCURRENCE} INTEGER,
{COLUMN_NAME_HOMOLOGY} INTEGER,
{COLUMN_NAME_COEXPRESSION} INTEGER,
{COLUMN_NAME_COEXPRESSION_TRANSFERRED} INTEGER,
{COLUMN_NAME_EXPERIMENTAL} INTEGER,
{COLUMN_NAME_EXPERIMENTAL_TRANSFERRED} INTEGER,
{COLUMN_NAME_DATABASE} INTEGER,
{COLUMN_NAME_DATABASE_TRANSFERRED} INTEGER,
{COLUMN_NAME_TEXTMINING} INTEGER,
{COLUMN_NAME_TEXTMINING_TRANSFERRED} INTEGER,
{COLUMN_NAME_COMBINED_SCORE} INTEGER,
PRIMARY KEY ({COLUMN_NAME_PROTEIN_A}, {COLUMN_NAME_PROTEIN_B})
"""

TABLE_INDEX_STRING_INTERACTIONS = f"""
CREATE INDEX ON {TABLE_NAME_STRING_INTERACTIONS} ({COLUMN_NAME_PROTEIN_A});
CREATE INDEX ON {TABLE_NAME_STRING_INTERACTIONS} ({COLUMN_NAME_PROTEIN_B})
"""


# Experimental Condition table
TABLE_NAME_EXPERIMENTAL_CONDITION = "experimental_condition"

COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME = "condition_name"
COLUMN_NAME_EXPERIMENTAL_CONDITION_DESCRIPTION = "description"
COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE = "type"

TABLE_STRUCTURE_EXPERIMENTAL_CONDITION = f"""
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) PRIMARY KEY,
{COLUMN_NAME_EXPERIMENTAL_CONDITION_DESCRIPTION} TEXT,
{COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE} VARCHAR(255),
CONSTRAINT {COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE}_check CHECK (
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_TYPE} IN (
        'transcriptomics',
        'proteomics',
        'phosphoproteomics'
    )
)
"""


# Transcriptomics table
TABLE_NAME_TRANSCRIPTOMICS = "transcriptomics"

COLUMN_NAME_EXPERIMENTAL_ID = "experimental_id"
COLUMN_NAME_CONDITION_A = "condition_a"
COLUMN_NAME_CONDITION_B = "condition_b"
COLUMN_NAME_LOG2_FOLD_CHANGE = "log2_fold_change"
COLUMN_NAME_P_VALUE = "p_value"
COLUMN_NAME_ADJUSTED_P_VALUE = "adjusted_p_value"

TABLE_STRUCTURE_TRANSCRIPTOMICS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_CONDITION_A} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_CONDITION_B} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_LOG2_FOLD_CHANGE} DOUBLE PRECISION,
{COLUMN_NAME_P_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_ADJUSTED_P_VALUE} DOUBLE PRECISION,
PRIMARY KEY ({COLUMN_NAME_EXPERIMENTAL_ID}, {COLUMN_NAME_CONDITION_A}, {COLUMN_NAME_CONDITION_B})
"""


# Transcriptomics Counts table
TABLE_NAME_TRANSCRIPTOMICS_COUNTS = "transcriptomics_counts"

COLUMN_NAME_REPLICATE = "replicate"
COLUMN_NAME_READ_COUNT = "read_count"
COLUMN_NAME_NORMALIZED_READ_COUNT = "normalized_read_count"

TABLE_STRUCTURE_TRANSCRIPTOMICS_COUNTS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_REPLICATE} INTEGER,
{COLUMN_NAME_READ_COUNT} DOUBLE PRECISION,
{COLUMN_NAME_NORMALIZED_READ_COUNT} DOUBLE PRECISION,
PRIMARY KEY ({COLUMN_NAME_EXPERIMENTAL_ID}, {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}, {COLUMN_NAME_REPLICATE})
"""


# Proteomics Peptide Modifications table
TABLE_NAME_PROTEOMICS_PEPTIDE_MODIFICATIONS = "proteomics_peptide_modifications"

# COLUMN_NAME_EXPERIMENTAL_ID
# EXPERIMENTAL_CONDITION_NAME
COLUMN_NAME_MODIFICATION_TYPE = "modification_type"
COLUMN_NAME_MODIFICATION_POSITION = "modification_position"
COLUMN_NAME_PEPTIDE_SEQUENCE = "peptide_sequence"
COLUMN_NAME_START_POSITION_COMPLETE_PROTEIN = "start_position_complete_protein"
COLUMN_NAME_END_POSITION_COMPLETE_PROTEIN = "end_position_complete_protein"
COLUMN_NAME_PSM_AMBIGUITY = "psm_ambiguity"
COLUMN_NAME_PEP = "pep"
COLUMN_NAME_Q_VALUE = "q_value"
COLUMN_NAME_SEARCH_ENGINE_CONFIDENCE = "search_engine_confidence"

TABLE_STRUCTURE_PROTEOMICS_PEPTIDE_MODIFICATIONS = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_MODIFICATION_TYPE} VARCHAR(255),
{COLUMN_NAME_MODIFICATION_POSITION} TEXT,
{COLUMN_NAME_PEPTIDE_SEQUENCE} TEXT,
{COLUMN_NAME_START_POSITION_COMPLETE_PROTEIN} INTEGER,
{COLUMN_NAME_END_POSITION_COMPLETE_PROTEIN} INTEGER,
{COLUMN_NAME_PSM_AMBIGUITY} TEXT,
{COLUMN_NAME_PEP} DOUBLE PRECISION,
{COLUMN_NAME_Q_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_SEARCH_ENGINE_CONFIDENCE} TEXT,
PRIMARY KEY (
    {COLUMN_NAME_EXPERIMENTAL_ID},
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME},
    {COLUMN_NAME_MODIFICATION_TYPE},
    {COLUMN_NAME_MODIFICATION_POSITION}
)
"""


# Proteomics Quantification table
TABLE_NAME_PROTEOMICS_QUANTIFICATION = "proteomics_quantification"

# COLUMN_NAME_EXPERIMENTAL_ID
# EXPERIMENTAL_CONDITION_NAME
# COLUMN_NAME_REPLICATE
COLUMN_NAME_PROTEIN_SEQUENCE = "protein_sequence"
COLUMN_NAME_SUM_PEP = "sum_pep"
COLUMN_NAME_COMBINED_Q_VALUE = "combined_q_value"
COLUMN_NAME_ABUNDANCE = "abundance"
COLUMN_NAME_ABUNDANCE_NORMALIZED = "abundance_normalized"
COLUMN_NAME_ABUNDANCE_COUNT = "abundance_count"


TABLE_STRUCTURE_PROTEOMICS_QUANTIFICATION = f"""
{COLUMN_NAME_EXPERIMENTAL_ID} VARCHAR(20),
{COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME} VARCHAR(255) REFERENCES {TABLE_NAME_EXPERIMENTAL_CONDITION}({COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME}),
{COLUMN_NAME_REPLICATE} INTEGER,
{COLUMN_NAME_PROTEIN_SEQUENCE} TEXT,
{COLUMN_NAME_SUM_PEP} DOUBLE PRECISION,
{COLUMN_NAME_COMBINED_Q_VALUE} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE_NORMALIZED} DOUBLE PRECISION,
{COLUMN_NAME_ABUNDANCE_COUNT} DOUBLE PRECISION,
PRIMARY KEY (
    {COLUMN_NAME_EXPERIMENTAL_ID},
    {COLUMN_NAME_EXPERIMENTAL_CONDITION_NAME},
    {COLUMN_NAME_REPLICATE},
    {COLUMN_NAME_PROTEIN_SEQUENCE}
)
"""

